### ISSUE TITLE
This framework vs. the official implementation

### ISSUE THREAD

**Issue by MostHated** [dimmpixeye/actors#18]
Hey there,
   I was curious as it looks like a lot of work went into this and it really shows, why might someone consider using a framework like this over the official Unity ECS implementation with Burst capability? I had not really thought about it before, is it at all possible for systems other than the official ECS to take advantage of Burst? Is someone able to take advantage of things like multiple separate worlds, Unity's newer physics, the new incarnation of scene serialization and streaming, etc?

Thanks!
-MH

**Comment by dimmpixeye** [comment]
Hi! thanks for the interested.
The intention of creating Actors was to provide an easily maintain approach for game development. I don't care much about Unity stack or how Burst works. I simply don't need it in my game production so I don't bother. As far as I remember Burst will work with any structured types in the future.  As components in Actors can be structures I guess there is a way to work around Burst. I know a few developers that are using Actors + Jobs. 

Also, Actors have a trick up its sleeve: multi-threaded groups

```csharp
sealed class ProcessorTest : Processor, ITick
	{
		public Group<ComponentPosition> groupThreaded;

		public ProcessorTest()
		{
			groupThreaded.MakeConcurrent(100000, Environment.ProcessorCount - 1, HandleCalculation);
		}


		public void Tick(float delta)
		{
			if (Input.GetKeyDown(KeyCode.Alpha1))
			{
				for (int i = 0; i < 500000; i++)
				{
					var e = Entity.Create();
					e.Set<ComponentPosition>();
				}
			}

			// One thread
			if (Input.GetKeyDown(KeyCode.Alpha2))
			{
				for (int i = 0; i < groupThreaded.length; i++)
				{
					ref var entity    = ref groupThreaded.entities[i];
					ref var cPosition = ref entity.ComponentPosition();
					for (int j = 0; j < 1000; j++)
					{
						cPosition.pos.x += 1 * delta;
					}
				}
			}

			// Multyhtread
			if (Input.GetKeyDown(KeyCode.Alpha3))
				groupThreaded.Execute(delta);
		}

		static void HandleCalculation(SegmentGroup segment)
		{
			for (int i = segment.indexFrom; i < segment.indexTo; i++)
			{
				ref var entity    = ref segment.source.entities[i];
				ref var cPosition = ref entity.ComponentPosition();
				for (int j = 0; j < 1000; j++)
				{
					cPosition.pos.x += 1 * segment.delta;
				}
			}
		}
	}
```

**Comment by dimmpixeye** [comment]
I'm eating my own dog food and develop games using Actors. So I evolve Actors and keep it up to date with Unity ( 2019.2 for now ) I always think about improving performance if it's possible but my personal killer feature is not Burst or something tech-related: it's clean code and productivity.  Feel free to ask any related questions and you can take a look at the game I currently work on: 

[![Image from Gyazo](https://i.gyazo.com/036899cdf7e545b724f2f64a6f6cf2de.gif)](https://gyazo.com/036899cdf7e545b724f2f64a6f6cf2de)
